# Generated by Django 4.2 on 2025-12-12 10:31

from django.db import migrations, models


def populate_usernames(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        # Use email as username if it exists, otherwise use id
        username = getattr(user, 'email', None) or f'user_{user.id}'
        # Ensure uniqueness
        base_username = username
        counter = 1
        while User.objects.filter(username=username).exists():
            username = f'{base_username}_{counter}'
            counter += 1
        user.username = username
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='temp', max_length=150),
        ),
        migrations.RunPython(populate_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
