# Generated by Django 4.2 on 2025-12-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_cartitem_product_alter_transactionitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
