# Generated by Django 4.2 on 2025-12-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produks', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
