# Generated by Django 4.2 on 2025-12-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_cartitem_product_alter_transactionitem_product'),
        ('produks', '0004_gudangproduct_kantinproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='kantinproduct',
            name='product_gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kantin_products', to='produks.gudangproduct'),
        ),
    ]
